<?php declare(strict_types=1);

/**
 * loki/magento2-base
 * Version: 1.0.4
 * Copyright: 2025 Jisse Reitsma
 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$jsUrl = $block->getViewFileUrl('MageOS_AlpineLoader::js/alpine-csp.js');
$defer = (bool)$block->getDefer();
?>
<script defer src="<?= /* @noEscape */ $jsUrl ?>" <?php if ($defer) : ?>defer<?php endif; ?>></script>
