<?php declare(strict_types=1);

/**
 * loki/magento2-base
 * Version: 1.0.4
 * Copyright: 2025 Jisse Reitsma
 */

use Magento\Framework\View\Element\Template;
use MageOS\AlpineJS\Util\CurrentTheme;

/** @var Template $block */
/** @var CurrentTheme $currentTheme */
$currentTheme = $block->getCurrentTheme();
if ($currentTheme->isHyva()) {
    return;
}

$jsUrl = $block->getViewFileUrl('MageOS_AlpineLoader::js/alpine-csp.js');
$defer = (bool)$block->getDefer();
?>
<script defer src="<?= /* @noEscape */ $jsUrl ?>" <?php if ($defer) : ?>defer<?php endif; ?>></script>
