<?php
declare(strict_types=1);

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\AlpineLoader\Util\FormKeyValue;
use MageOS\AlpineLoader\Util\LocaleCode;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 1.1.11 */
/** @var Template $block */
/** @var FormKeyValue $formKeyValue */
/** @var LocaleCode $localeCode */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

$formKeyValue = $block->getFormKeyValue();
$localeCode = $block->getLocaleCode();
$mobileWidth = $block->getMobileWidth();
if (!is_numeric($mobileWidth) || $mobileWidth < 100) {
    $mobileWidth = 767;
}

$script = '';
$script .= "var CURRENT_LOCALE = '".$escaper->escapeUrl($localeCode->getCode())."';";
$script .= "var FORM_KEY = '".$escaper->escapeHtml($formKeyValue->get())."';";
$script .= "var CURRENT_URL = window.location.href.split('?')[0];";
$script .= "var IS_MOBILE = ((window.innerWidth > 0) ? window.innerWidth : screen.width) < ". (int)$mobileWidth.";";
echo $secureRenderer->renderTag('script', [], $script, false);

